### ISSUE TITLE
Unable to build: use of undelcared type 'ObserverOf'

### ISSUE THREAD

**Issue by m-revetria** [bontoJR/RxAlamofire#2]
Hi!

I'm getting this build error "Use of undeclared type 'ObserverOf'" on Request extension in all `rx_` methods, e.g.:

Request.swift
line 26: `return create { (observer: ObserverOf<NSData>) -> Disposable in`

Currenlty I installed Alamofire v2.0.1 and RxSwift 2.0.0-beta via cocoapods v 0.39.0

How could I fix this error?

**Comment by bontoJR** [comment]
Hi @m-revetria,

RxSwift 2.0.0-beta requires Alamofire 3.0+ to work.

If you need to use 2.0.1 with RxSwift 2.0.0-beta you need to change `(observer: ObserverOf<NSData>) -> Disposable in` to `observer -> Disposable in`.

**Comment by bontoJR** [comment]
Hi @m-revetria, 
do you still need help?
